name: Welcome New Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write      # Grants permission to post comments
      pull-requests: write  # Grants permission to interact with PRs

    steps:
    - name: Post welcome message
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ github.event.pull_request.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ":wave: Welcome @${{ github.event.pull_request.user.login }}! Thanks for opening this pull request."
          })
