name: Welcome New Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
    - name: Comment welcome message
      uses: peter-evans/comment-pr@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :wave: Welcome @${{ github.event.pull_request.user.login }}! Thanks for opening this pull request. We're excited to see what you've got!
